Added David J Harding to contributors
covidgreen/covid-green-app pull request #16
Opened 2020-07-31 20:43 UTC by dharding

2020-07-31 21:25 UTC, jasnell requested changes
The contributors lists the members of the @covidgreen/members team (folks with commit bits that aren't in the leads or core team). That's done as part of the onboarding process once you've been nominated and approved as a contributor. You can self nominate yourself as a contributor by opening an issue that includes a bit of background of yourself and the contributions you've made or plan to make. Generally, however, we need to see some activity before accepting self-nominations

2020-07-31 21:27 UTC, jasnell commented
(btw, the "Request Changes" is temporary here... will keep this open until we can go through a contribution nomination)

2020-07-31 21:45 UTC, jasnell commented
Nomination thread here: https://github.com/covidgreen/covid-green-app/issues/19

2020-08-03 14:12 UTC, jasnell approved these changes

2020-08-03 14:15 UTC, floridemai approved these changes

2020-08-03 14:17 UTC, merged