feat: migrate to SVG icons (WIP)
covidgreen/covid-green-app pull request #22
Opened 2020-08-05 13:48 UTC by jh3y

- Pull in SVG transformer and set up babel config
- Swap appropriate icons out where applicable
- Any app sweeps appreciated 👍  Think that some of the fill/stroke colors might require changing out.

2020-08-06 07:46 UTC, ckiss reviewed
good work @jh3y. I left a couple of comments in there, please have a look at let me know your thoughts.

2020-08-06 07:46 UTC, ckiss commented on assets/icons/app/alert.svg
> +</svg>
there are some files, like this one, where there is no newline at EOF, would be good to add them

2020-08-06 07:46 UTC, ckiss commented on assets/icons/index.ts
> +};
not entirely sure why need so many exports. Wouldn't be better to export all of them as default? will ease the import and usage a bit and also when you want to add a new icon you will not have to think about where it fits better.

2020-08-06 07:46 UTC, ckiss commented on components/atoms/card.tsx
> +  icon?: ReactNode;
would be good to have our own specific type for the `icon`

2020-08-06 08:28 UTC, floridemai requested changes
The icons come in to replace existing pngs. We should remove those part of this PR imho.
Another thing that we should probably do is to run all svgs through `SVGO` and document that to be part of adding an icon.

2020-08-06 14:13 UTC, jh3y commented
@floridemai Updated, wiped cache, removed unused png, added `optimize:svg` run script to run against icons folder 👍

2020-08-07 08:22 UTC, ckiss commented
@jh3y @floridemai I tested and works fine. I can't approve though :D LGTM!

2020-08-07 08:32 UTC, floridemai approved these changes
@jh3y Thanks for the follow-ups, looks really good

2020-08-07 08:35 UTC, ShaunBaker approved these changes

2020-08-07 09:30 UTC, merged